name: Deploy Frontend to VPS

on:
  push:
    branches:
      - production  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies & build
        run: |
          echo "VITE_PUBLIC_STRAPI_API_URL=${{ secrets.VITE_PUBLIC_STRAPI_API_URL }}" > .env
          npm ci
          npm run build

      - name: Copy files to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}  # renamed correctly
          source: "dist/*"
          target: "/var/www/didihat-frontend"
          strip_components: 1
